[package]
name = "bytelabs"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "bytelabs"
path = "src/main.rs"

[dependencies]
gpui.workspace = true

[package.metadata.bundle]
icon = ["resources/app-icon@2x.png", "resources/app-icon.png"]
identifier = "uk.co.bytelabs"
name = "ByteLabs"
osx_minimum_system_version = "10.15.7"
osx_info_plist_exts = ["resources/info/*"]
osx_url_schemes = ["uk.co.bytelabs"]
